POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video aleatorio",
    "description": "sem palavras para consulta",
    "duration": 60    
}

###


GET  http://localhost:3333/videos?search=

###

PUT http://localhost:3333/videos/a86e1544-0052-416a-9367-f0a5a042b8e6
Content-Type: application/json

{
    "title": "Pure node",
    "description": "random text",
    "duration": 5    
}

###

DELETE http://localhost:3333/videos/34df7aab-9d57-4cc7-9e9b-c62d7a0d2dc5
